site_name: IVAC2 EBBU FIRDEF Manual
pages:
    - Home: index.md
    - About: about.md
theme: 'united'
site_author: Jessy Stas
site_url: https://diesel8.github.io/IVAC2-EBBU-FIRDEF-Manual/
edit_uri: edit/master/docs/

# Theme

      
# Repository
repo_name: Diesel8/IVAC2-EBBU-FIRDEF-Manual
repo_url: https://github.com/Diesel8/IVAC2-EBBU-FIRDEF-Manual

# Copyright
copyright: 'Copyright &copy; 2017 Jessy Stas'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - admonition
  - codehilite(guess_lang=false)
- toc(permalink=true)